# Generated by Django 4.0.5 on 2022-06-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0002_alter_client_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('categories', models.CharField(choices=[('Anxiety', 'Anxiety'), ('Troumatic Experience', 'Troumatic Experience'), ('Relationship', 'Relationship'), ('School or Work Stress', 'School or Work Stress'), ('Depression', 'Depression'), ('Addiction', 'Addiction'), ('Other', 'Other')], default='Other', max_length=255)),
                ('article', models.FileField(upload_to='articles')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.counsellor')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
