# Generated by Django 4.0.5 on 2022-06-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anxiety', models.BooleanField(default=False)),
                ('troumatic_experience', models.BooleanField(default=False)),
                ('relationship', models.BooleanField(default=False)),
                ('stress', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('addiction', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.client')),
            ],
        ),
    ]
