# Generated by Django 4.0.5 on 2022-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0005_alter_article_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('8-9am', '8-9am'), ('9-10am', '9-10am'), ('10-11am', '10-11am'), ('11-12pm', '11-12pm'), ('12-1pm', '12-1pm'), ('1-2pm', '1-2pm'), ('2-3pm', '2-3pm'), ('3-4pm', '3-4pm'), ('4-5pm', '4-5pm')], default='8-9am', max_length=255),
        ),
    ]
